TRADER_ID = 0
ORDER_ID = 0
TIME = 1
# TIME_FRAME = 60 # i.e 1 candle represents 60 seconds
# TIME_FRAME = 10 # i.e 1 candle represents 60 seconds
TIME_FRAME = 10 # i.e 1 candle represents 60 seconds

# SHORTING_MARGIN_PERCENTAGE = 0.2 # i.e in shorting some ma


# -1 -> extreme bearish 1 -> extreme bullish
MARKET_SENTIMENT = 0 # if below 0 means negativity in market for the company, and most trader will sell opposite for buying

DAY_LENGTH = 24 # represents total no of candles which represents one day
DAY_LENGTH_TICKS = 24 * TIME_FRAME # represents total no of ticks which represents one day

STARTING_PRICE = 100

# EMA PERIODS
EMA_PERIODS = [9,15,21,50]

# LEVEL 2 DATA Window
# WINDOW_LEVEL2_MAX_ROWS = 5
WINDOW_LEVEL2_MAX_ROWS = 20


# total shares available for trade
# TOTAL_SHARES = 1000000
TOTAL_SHARES = 200000

# EXCHANGE NOT IMPLEMENTED YET
MAKER_FEES = -0.001 # exchange give rebate to limit orders
TAKER_FEES = 0.003 # exchange fees for market takers. the ones who make market order

# RANDOM TRADER
# used to assign balance
# RANDOM_MIN_BALANCE = 10*STARTING_PRICE - 10
RANDOM_MIN_BALANCE = 50*STARTING_PRICE - 10
# RANDOM_MAX_BALANCE = 100*STARTING_PRICE
RANDOM_MAX_BALANCE = 1000*STARTING_PRICE

RANDOM_TRADERS = 20000 # traders quantity


# COMPANY
COMPANY_HOLDINGS = 100000
COMPANY_BALANCE = 100000000

# WHALES
WHALES_HOLDINGS_MIN = 5000
WHALES_HOLDINGS_MAX = 50000
WHALES_MIN_BALANCE = 50000
WHALES_MAX_BALANCE = 100000
WHALES = 50

# LEVEL1 TRADER -> BasicTrendFollowerTrader
MAX_LAST_CANDLE_VIEW = 5 # use to find a random no from 1 to this max no
LEVEL1_TRADER_LOSS = 0.2 # 20% max loss allowed after which sell
LEVEL1_TRADER_MIN_BALANCE = 1000
LEVEL1_TRADER_MAX_BALANCE = 10000
LEVEL1_TRADER_INTRADAY_MIN_THRESHOLD = (DAY_LENGTH - 2) * TIME_FRAME # the min ticks for a intraday after they must become ready to sell all holding before day ends
# LEVEL1_TRADERS = 5000
LEVEL1_TRADERS = 10000


# LEVEL2 TRADER
LEVEL2_TRADER_MIN_BALANCE = 5000
LEVEL2_TRADER_MAX_BALANCE = 50000
LEVEL2_TRADER_STOPLOSS = 0.2 # 20%

# LEVEL2_TRADERS = 5000
LEVEL2_TRADERS = 2500


# LIQUIDITY ABSORBER
LIQUIDITY_TRADERS = 100
# LIQUIDITY_TRADERS_MIN_BALANCE = 1000000
LIQUIDITY_TRADERS_MIN_BALANCE = 50000
# LIQUIDITY_TRADERS_MAX_BALANCE = 10000000
LIQUIDITY_TRADERS_MAX_BALANCE = 100000

# AGRESSIVE TRADER
# AGRESSIVE_TRADER = 500
AGRESSIVE_TRADER = 200
AGRESSIVE_TRADER_MIN_BALANCE = 30000
# AGRESSIVE_TRADER_MAX_ABALANCE = 10000000
AGRESSIVE_TRADER_MAX_ABALANCE = 100000

# BEARS
BEARS_TRADERS = 500
# BEARS_TRADERS = 0

# MARKET MAKERS
MARKET_MAKER = 100


# LEVEL3 TRADER
LEVEL3_TRADER_MIN_BALANCE = 100000
LEVEL3_TRADER_MAX_BALANCE = 10000000


